# Generated by Django 3.0 on 2019-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam_host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
